[project]
name = "mcp-ops-toolkit"
version = "0.1.0"
description = "A toolkit for MCP operations"
readme = "README.md"
requires-python = ">=3.11.7"
dependencies = [
    "mcp[cli]>=1.6.0",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]
